# Generated by Django 2.2.3 on 2019-08-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=200)),
                ('page_name', models.CharField(max_length=200)),
                ('page_birth', models.CharField(max_length=200)),
                ('page_nationality', models.CharField(max_length=200)),
                ('page_nameEn', models.CharField(max_length=200)),
                ('page_gradYear', models.CharField(max_length=200)),
                ('page_formOfStudy', models.CharField(max_length=200)),
                ('page_specialty', models.CharField(max_length=200)),
                ('page_prevDoc', models.CharField(max_length=200)),
                ('page_country', models.CharField(default='---', max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
