# Generated by Django 2.2.3 on 2019-07-30 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190728_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studId', models.CharField(max_length=200)),
                ('studName', models.CharField(max_length=200)),
                ('studFaculty', models.CharField(max_length=200)),
                ('studCourse', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Students Cards',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='studSlug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 16, 7, 47, 578186), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='StudSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studSeries', models.CharField(max_length=200)),
                ('studSeriesDescription', models.CharField(max_length=200)),
                ('studCard', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.StudCard', verbose_name='Series')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='studSeries',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.StudSeries', verbose_name='Series'),
        ),
    ]
