# Generated by Django 2.2.3 on 2019-07-28 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=200)),
                ('page_content', models.TextField()),
                ('page_published', models.DateTimeField(default=datetime.datetime(2019, 7, 28, 5, 2, 33, 832442), verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
