# Generated by Django 2.2.3 on 2019-07-28 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190728_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 28, 5, 3, 57, 475269), verbose_name='date published'),
        ),
    ]
